### ISSUE TITLE
Layout is wrong when used with tailwind

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#121]
### Describe the bug

![CleanShot 2022-12-21 at 12 24 15@2x](https://user-images.githubusercontent.com/24843808/208813642-7679d840-61eb-4a11-80a3-9dfe10b3ac10.png)

select, input, button, and textarea's size are wrong.

To fix this, we can use the below CSS style.

```css
.pdfme-designer select {
  font-size: 0.7rem;
  padding: 0;
  padding-left: 5px;
}

.pdfme-designer input {
  font-size: 0.8rem;
  padding: 2px;
  padding-left: 5px;
}

.pdfme-designer button {
  padding: 2px;
}

.pdfme-designer textarea {
  height: 50px !important;
  font-size: 0.75rem;
  line-height: 0.8rem;
  height: 65px;
}
```

### To Reproduce

Mount on TailwindCSS project.

### Expected behavior

Same layout if we use TailwindCSS or not.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/ui
- pdfme version: 1.0.17
- Operating system: MacOS
- Node.js version or Browser name & version: Chrome, Version 108.0.5359.124 (Official Build) (arm64)
```

### Your Error Log

```shell
No Error log
```
